/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GistCalculator */

#ifndef _Included_GistCalculator
#define _Included_GistCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GistCalculator
 * Method:    calculateGist
 * Signature: ([F[F[FII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_GistCalculator_calculateGist
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
